services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_mema_data:/data/d
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: pass
       ME_CONFIG_MONGODB_SERVER: mongodb
       ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb
  client:
    image: dutchman5/game_night_client:latest 
    environment:
       SERVER_URI: http://localhost:3001
    ports:
      - "3000:3000"
  server: 
    image: dutchman5/game_night_server:latest
    environment:
      MONGODB_URI: mongodb://admin:pass@mongodb:27017
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
volumes:
  mongo_mema_data:
